### ISSUE TITLE
Unrealistic PET values for options (2), (3) and (5) 

### ISSUE THREAD

**Issue by lcunha0118** [NOAA-OWP/evapotranspiration#12]
PET options (2) aerodynamic, (3) combined, and (5) Penman-Monteith methods are currently providing unreasonable PET values.  

## Current behavior
Table below shows PET mean annual values (mm/year) for selected CAMELS basins for the five PET options. PET options 2, 3 and 5 present unrealistically high PET values. 

![image](https://user-images.githubusercontent.com/8662550/163864862-af2c5717-0dfb-409b-abe8-90a98ab7cc51.png)

Possible causes: unit issues for the input or for the parameters in the config file.

**Comment by lcunha0118** [comment]
@ajkhattak please use PET options (1) or (4) for now.

**Comment by WanruWu-NOAA** [comment]
https://github.com/NOAA-OWP/evapotranspiration/commit/f2cee381c7bd1e67f0c91cb9fdb99ce8c520a22c

**Comment by SnowHydrology** [comment]
Closed with PR #13, #15, and #16.
