### ISSUE TITLE
Zero plane displacement heights in forests

### ISSUE THREAD

**Issue by SnowHydrology** [NOAA-OWP/evapotranspiration#14]
PET option 5, the Penman-Monteith method is optimized for relatively even grass/crop surfaces. In these areas, the zero plane displacement height, `d`, is typically less than the wind speed and/or relative humidity measurement height. This is important because estimating surface resistance, `rs`, requires taking the natural log of the measurement height, `z`, minus `d`. The natural log of a negative number (i.e., `d` > `z`) is NaN.

![image](https://user-images.githubusercontent.com/32177682/176678545-d58a34e7-fb41-416c-8939-eaf19298be35.png)

[Equation from FAO.](https://www.fao.org/3/x0490e/x0490e06.htm)

## Current behavior

When PET is run with option 5 in forested locations (`d` > `z`), it returns NaN. Part of this is because we are using AORC forcing data, which assumes `z` for wind is 10 m and `z` for humidity is 2 m. If running option 5 with above-canopy met towers, this would not be a problem.

## Expected behavior

We should be able to estimate PET in forested locations using P-M as other researchers have done. We need to either modify the `z` estimate to be less than the measurement height or substitute empirically derived resistance values. E.g., 43–67 s/m from [Amatya et al. (2016)](https://ascelibrary.org/doi/10.1061/%28ASCE%29HE.1943-5584.0001341).

**Comment by WanruWu-NOAA** [comment]
Thanks, Keith.  I'd like to add that the equation `ra` was the aerodynamic resistance; the surface resistance `rs` was assigned to a constant in /src/pet.c as `model->pet_forcing.canopy_resistance_sec_per_m   = 50.0`

**Comment by SnowHydrology** [comment]
Closed with PR #13, #15, and #16
