### ISSUE TITLE
time_step hard-coded to unit=seconds

### ISSUE THREAD

**Issue by madMatchstick** [NOAA-OWP/evapotranspiration#24]
Based off `get_time_step()` def [here](https://github.com/NOAA-OWP/evapotranspiration/blob/9ef56e369e2b8f766f523a1014a6713368fd5010/src/bmi_pet.c#L456), as well as any general search for `time_step_size_s`, seems like we are hard-coding an assumption for time step to be of units `s`.  

Is this is case?  If so, is this BMI compliant? 

Reminder to further look into spec/implementation

**Comment by SnowHydrology** [comment]
My read is that this is okay because the model, when built, has the `s` built in regardless from the BMI spec and its internal time handling assumes the time step is in seconds.

**Comment by peckhams** [comment]
I agree that this is fine, because the model can choose its own timestep
units as long as it is reported by the BMI function get_time_units().  That
allows the framework to convert time units, if that were necessary.
